version: "3.1"

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    restart: always
    image: postgres
    container_name: demo-postgres #you can change this
    environment:
      POSTGRES_DB: semantic_role_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: demo-pgadmin #you can change this
      depends_on:
        - db
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test@example.com
        PGADMIN_DEFAULT_PASSWORD: 1234
      restart: always

volumes:
  postgres_data:
